version: 1.0.{build}
image: Visual Studio 2017
platform:
- x86
- x64
clone_folder: C:\GOPATH\src\github.com\go-rillas\gor
environment:
  GOPATH: C:\GOPATH
  GOBIN: C:\GOPATH\bin
build_script:
- cmd: ECHO %PATH%
- cmd: ECHO %GOPATH%
- cmd: ECHO %GOBIN%
- cmd: set PATH=%GOBIN%;%PATH%
- cmd: ECHO %PATH%
- cmd: go get -v -t github.com/go-rillas/gor/...
test_script:
- cmd: go test -v ./...