version: 1.0.{build}
image: Visual Studio 2017
platform:
- x86
- x64
clone_folder: C:\GOPATH\src\github.com\go-rillas\gor
environment:
  GOPATH: C:\GOPATH
  GOBIN: C:\GOPATH\bin
build_script:
#- cmd: go get -v -t github.com/go-rillas/gor/...
#- cmd: gor.exe -h
- ps: go get -v -t github.com/go-rillas/gor/...
- ps: gor.exe -h
test_script:
- ps: go test -v ./...