version: 1.0.{build}
image: Visual Studio 2017
platform:
- x86
- x64
clone_folder: C:\GOPATH\src\github.com\go-rillas\gor
environment:
  GOPATH: C:\GOPATH
  GOBIN: %GOPATH%\bin
build_script:
- cmd: go get -v -t github.com/go-rillas/gor/...
- cmd: gor.exe -h
- ps: gor.exe -h
test_script:
- cmd: go test -v ./...