version: 1.0.{build}
image: Visual Studio 2017
platform:
- x86
- x64
clone_folder: C:\GOPATH\src\github.com\go-rillas\gor
environment:
  GOPATH: C:\GOPATH
  GOBIN: C:\GOPATH\bin
build_script:
- cmd: set PATH=%GOBIN%;%PATH%
- cmd: go get -v -t github.com/go-rillas/gor/...
- cmd: assoc .gor=gor.exe
#- cmd: C:\GOPATH\bin\gor.exe -h
#- cmd: gor.exe -h
test_script:
- cmd: go test -v ./...